controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: position_controllers/GripperActionController
      joints:
        - Left_1_Joint
      action_monitor_rate: 20
      goal_tolerance: 0.01
      max_effort: 100
      allow_partial_joints_goal: false
      state_publish_rate: 50
      action_deadline: 10.0
      default_goal_tolerance: 0.01
      default_stopped_velocity_tolerance: 0.01
      default_goal_time_tolerance: 0.0
