/**:
  ros__parameters:
    elfin_ethernet_name: enx0
    slave_no: [1, 2, 3]
    joint_names:
      [
        elfin_joint2,
        elfin_joint1,
        elfin_joint3,
        elfin_joint4,
        elfin_joint5,
        elfin_joint6
      ]

controller_manager:
  ros__parameters:
    update_rate: 250

    elfin_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
      publish_rate: 50
      write_op_modes:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: position_controllers/GripperActionController
      is_async: true

gripper_controller:
  ros__parameters:
    joint: Left_1_Joint
    allow_stalling: true
    is_async: true
    update_rate: 10
    constraints:
      Left_1_Joint: { trajectory: 0.9, goal: 0.9 }

elfin_arm_controller:
  ros__parameters:
    joints:
      - elfin_joint1
      - elfin_joint2
      - elfin_joint3
      - elfin_joint4
      - elfin_joint5
      - elfin_joint6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 250.0
    action_monitor_rate: 250.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.6
      elfin_joint1: { trajectory: 0.2, goal: 0.1 }
      elfin_joint2: { trajectory: 0.2, goal: 0.1 }
      elfin_joint3: { trajectory: 0.2, goal: 0.1 }
      elfin_joint4: { trajectory: 0.2, goal: 0.1 }
      elfin_joint5: { trajectory: 0.2, goal: 0.1 }
      elfin_joint6: { trajectory: 0.2, goal: 0.1 }
